stages:
    - backendtest
    - backendlint
    - frontendtest
    - frontendlint

test:
    stage: backendtest
    script:
        - cd ./server
        - python3 -m coverage run --source="." manage.py test --noinput
        - python3 -m coverage report

lint:
    stage: backendlint
    script:
        - cd ./server
        - pylint --rcfile=.pylintrc ./**/*.py
    allow_failure: false

test2:
    stage: frontendtest
    script:
        - cd ./frontend
        - npm install
        - npm test

lint2:
    stage: frontendlint
    script:
        - cd ./frontend
        - npm install
        - npm run lint
    allow_failure: false

