# Generated by Django 2.1 on 2018-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_time',
            field=models.PositiveIntegerField(default=1535359721),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.PositiveIntegerField(verbose_name=1535359721),
        ),
    ]
