# Generated by Django 2.1 on 2018-08-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180816_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_alias',
            new_name='nickname',
        ),
    ]
